server:
  port: 8080

spring:
# Application Name
  application:
    name: API-GATEWAY
# Routing to different services as per the request
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

  # For Config Server
  config:
    import: optional:configserver:http://localhost:8084

# Octa Configuration for API Gateway
okta:
  oauth2:
    issuer: https://dev-27631982.okta.com/oauth2/default
    audience: api://default
    client-id:
    client-secret:
    scopes: openid, profile, email, offline_access