spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_rating_data
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Application Name
  application:
    name: RATING-SERVICE

  # For Config Server
  config:
    import: optional:configserver:http://localhost:8084

server:
  port: 8083

# Octa Configuration for API Gateway
okta:
  oauth2:
    issuer: https://dev-27631982.okta.com/oauth2/default
    audience: api://default